In [1]:
import pandas as pd
import numpy as np

# Database Ingestion

In [3]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# My SQL Server settings (Windows Authentication)
server = "LAPTOP-RINT5KD3"   
database = "Silent_Struggles"

# Driver
driver = quote_plus("ODBC Driver 17 for SQL Server")

# SQLAlchemy connection string for Windows Authentication
engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver}&trusted_connection=yes"
)

In [4]:
df = pd.read_sql("select * from Adolescent_Mental_Health_In_Bangladesh", engine)
df

,record_id,age,dob,sex,father_quali,father_occu,mother_quali,mother_occu,marital_status,income,...,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height,weight,bp_sys,bp_dia,pulse
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,...,-1,6,-1,6,-1,63.000000,44.400002,105,65,74
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,...,-1,6,-1,6,-1,68.000000,67.300003,123,78,69
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,...,-1,6,-1,6,-1,61.000000,59.500000,98,60,77
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,...,-1,6,-1,6,-1,61.000000,52.000000,98,62,84
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,...,-1,6,-1,6,-1,57.000000,48.700001,112,75,103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,40017,16,2006-09-25,1,3,8,4,11,1,10000,...,-1,6,-1,6,-1,58.799999,46.000000,109,66,79
2026,40018,16,2005-03-28,1,3,15,1,11,5,3000,...,-1,6,-1,6,-1,57.500000,36.000000,103,63,95
2027,50010,14,2006-05-28,1,3,3,2,11,1,20000,...,-1,6,-1,6,-1,67.000000,93.000000,107,62,81
2028,90114,15,2008-06-06,1,2,9,2,11,1,13000,...,-1,6,-1,6,-1,55.000000,42.000000,120,75,84
2029,90117,14,2007-04-08,1,1,5,1,11,1,15000,...,-1,6,-1,6,-1,62.000000,45.000000,118,74,89

# Understanding the Dataset

In [6]:
df.head()

,record_id,age,dob,sex,father_quali,father_occu,mother_quali,mother_occu,marital_status,income,...,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height,weight,bp_sys,bp_dia,pulse
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,...,-1,6,-1,6,-1,63.0,44.400002,105,65,74
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,...,-1,6,-1,6,-1,68.0,67.300003,123,78,69
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,...,-1,6,-1,6,-1,61.0,59.500000,98,60,77
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,...,-1,6,-1,6,-1,61.0,52.000000,98,62,84
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,...,-1,6,-1,6,-1,57.0,48.700001,112,75,103

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Columns: 113 entries, record_id to pulse
dtypes: bool(5), float64(3), int64(104), object(1)
memory usage: 1.7+ MB

In [8]:
df.shape

(2030, 113)

In [9]:
df.describe(include="all")

,record_id,age,dob,sex,father_quali,father_occu,mother_quali,mother_occu,marital_status,income,...,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height,weight,bp_sys,bp_dia,pulse
count,2030.000000,2030.000000,2030,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,...,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000
unique,NaN,NaN,1123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,2006-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,8477.724138,15.514778,NaN,0.607389,4.726601,6.331034,3.184729,10.290640,1.427586,18520.745813,...,-0.873892,5.925616,-0.814286,5.941872,-0.885222,61.503202,47.959405,110.966995,72.945320,86.870443
std,5855.954202,1.319949,NaN,0.488452,11.902207,5.309334,4.784551,3.506842,3.477510,15693.099292,...,0.749475,0.458084,2.412693,0.413630,1.025610,3.617982,10.225798,12.331202,9.338942,14.212756
min,1001.000000,14.000000,NaN,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3000.000000,...,-1.000000,1.000000,-1.000000,1.000000,-1.000000,40.000000,26.299999,66.000000,43.000000,41.000000
25%,4119.250000,14.000000,NaN,0.000000,2.000000,3.000000,2.000000,11.000000,1.000000,10000.000000,...,-1.000000,6.000000,-1.000000,6.000000,-1.000000,59.000000,41.000000,103.000000,67.000000,77.000000
50%,8045.500000,15.000000,NaN,1.000000,3.000000,5.000000,3.000000,11.000000,1.000000,15000.000000,...,-1.000000,6.000000,-1.000000,6.000000,-1.000000,61.000000,46.000000,111.000000,73.000000,86.000000
75%,11129.750000,16.000000,NaN,1.000000,4.000000,8.000000,4.000000,11.000000,1.000000,20000.000000,...,-1.000000,6.000000,-1.000000,6.000000,-1.000000,64.000000,53.000000,119.000000,79.000000,96.000000
max,90117.000000,19.000000,NaN,1.000000,88.000000,88.000000,88.000000,88.000000,88.000000,250001.000000,...,15.000000,6.000000,100.000000,6.000000,20.000000,76.000000,101.000000,158.000000,131.000000,149.000000

# Rename Columns

In [176]:
df = df.rename(columns={
    "father_quali": "father_qualification",
    "father_occu": "father_occupation",
    "mother_quali": "mother_qualification",
    "mother_occu": "mother_occupation",
    "bro": "brother",
    "sis": "sister",

    "Cat_SWEMWS": "categorical_SWEMWS",
    "Cat_AIS": "categorical_AIS",
    "Cat_FIES": "categorical_FIES",
    "Cat_stress": "categorical_stress",
    "Cat_Depression": "categorical_Depression",
    "Cat_Anxiety": "categorical_Anxiety",

    "height": "height(inch)",
    "weight": "weight(kg)"
})

In [12]:
df.head()

,record_id,age,dob,sex,father_qualification,father_occupation,mother_qualification,mother_occupation,marital_status,income,...,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height,weight,bp_sys,bp_dia,pulse
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,...,-1,6,-1,6,-1,63.0,44.400002,105,65,74
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,...,-1,6,-1,6,-1,68.0,67.300003,123,78,69
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,...,-1,6,-1,6,-1,61.0,59.500000,98,60,77
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,...,-1,6,-1,6,-1,61.0,52.000000,98,62,84
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,...,-1,6,-1,6,-1,57.0,48.700001,112,75,103

# Handle Missing Values

In [14]:
# df.isnull().sum()      -> I have too many columns. So it didn't show every colunm is the result. That's why I am using below step to see every column.
with pd.option_context("display.max_rows", None):
    print(df.isnull().sum())

record_id                    0
age                          0
dob                          0
sex                          0
father_qualification         0
father_occupation            0
mother_qualification         0
mother_occupation            0
marital_status               0
income                       0
brother                      0
sister                       0
family_member_male           0
family_member_female         0
telephone                    0
mobile                       0
television                   0
radio                        0
car                          0
motor_cycle                  0
bicycle                      0
categorical_SWEMWS           0
categorical_AIS              0
alabama1                     0
alabama2                     0
alabama3                     0
alabama4                     0
alabama5                     0
alabama6                     0
alabama7                     0
alabama8                     0
alabama9                     0
food1                        0
food2                        0
food3                        0
food4                        0
food5                        0
food6                        0
food7                        0
food8                        0
categorical_FIES             0
categorical_stress           0
categorical_Depression       0
categorical_Anxiety          0
cyber_abuse                  0
cyber_abuse_2                0
cyber_abuse_3_1              0
cyber_abuse_3_2              0
cyber_abuse_3_3              0
cyber_abuse_3_4              0
cyber_abuse_3_5              0
cyber_abuse_4                0
cyber_abuse_5_1              0
cyber_abuse_5_2              0
cyber_abuse_5_3              0
cyber_abuse_6                0
cyber_abuse_7_1              0
cyber_abuse_7_2              0
cyber_abuse_7_3              0
cyber_abuse_7_4              0
cyber_abuse_7_5              0
cyber_abuse_7b_1             0
cyber_abuse_7b_2             0
cyber_abuse_7b_3             0
cyber_abuse_8                0
cyber_abuse_9_1              0
cyber_abuse_9_2              0
cyber_abuse_9_3              0
cyber_abuse_9_4              0
cyber_abuse_10               0
cyber_abuse_11            1629
cyber_abuse_13               0
cyber_abuse_14               0
cyber_abuse_15               0
cyber_threat_1               0
cyber_threat_2_0             0
cyber_threat_2_1             0
cyber_threat_2_2             0
cyber_threat_2_3             0
cyber_threat_2_4             0
cyber_threat_2_5             0
cyber_threat_2_6             0
cyber_threat_2_7             0
cyber_threat_2_8             0
cyber_threat_3               0
cyber_threat_4_0             0
cyber_threat_4_1             0
cyber_threat_4_2             0
cyber_threat_4_3             0
cyber_threat_4_4             0
cyber_threat_4_5             0
cyber_threat_4_6             0
abuse_deg_1                  0
abuse_deg_1a                 0
abuse_deg_2                  0
abuse_deg_2a                 0
abuse_deg_3                  0
abuse_deg_3a                 0
abuse_deg_4                  0
abuse_deg_4a                 0
abuse_deg_5                  0
abuse_deg_5a                 0
abuse_deg_6                  0
abuse_deg_6a                 0
abuse_deg_7                  0
abuse_deg_7a                 0
abuse_deg_8                  0
abuse_deg_8a                 0
height                       0
weight                       0
bp_sys                       0
bp_dia                       0
pulse                        0
dtype: int64

In [15]:
# Let's consider that "-1" is indicating to missing values in the dataset. 
# So, I am going to fill all the missing values with "-1".

df['cyber_abuse_11'] = df['cyber_abuse_11'].fillna(-1)

In [16]:
# after handling missing values from "cyber_abuse_11"

with pd.option_context("display.max_rows", None):
    print(df.isnull().sum())

record_id                 0
age                       0
dob                       0
sex                       0
father_qualification      0
father_occupation         0
mother_qualification      0
mother_occupation         0
marital_status            0
income                    0
brother                   0
sister                    0
family_member_male        0
family_member_female      0
telephone                 0
mobile                    0
television                0
radio                     0
car                       0
motor_cycle               0
bicycle                   0
categorical_SWEMWS        0
categorical_AIS           0
alabama1                  0
alabama2                  0
alabama3                  0
alabama4                  0
alabama5                  0
alabama6                  0
alabama7                  0
alabama8                  0
alabama9                  0
food1                     0
food2                     0
food3                     0
food4                     0
food5                     0
food6                     0
food7                     0
food8                     0
categorical_FIES          0
categorical_stress        0
categorical_Depression    0
categorical_Anxiety       0
cyber_abuse               0
cyber_abuse_2             0
cyber_abuse_3_1           0
cyber_abuse_3_2           0
cyber_abuse_3_3           0
cyber_abuse_3_4           0
cyber_abuse_3_5           0
cyber_abuse_4             0
cyber_abuse_5_1           0
cyber_abuse_5_2           0
cyber_abuse_5_3           0
cyber_abuse_6             0
cyber_abuse_7_1           0
cyber_abuse_7_2           0
cyber_abuse_7_3           0
cyber_abuse_7_4           0
cyber_abuse_7_5           0
cyber_abuse_7b_1          0
cyber_abuse_7b_2          0
cyber_abuse_7b_3          0
cyber_abuse_8             0
cyber_abuse_9_1           0
cyber_abuse_9_2           0
cyber_abuse_9_3           0
cyber_abuse_9_4           0
cyber_abuse_10            0
cyber_abuse_11            0
cyber_abuse_13            0
cyber_abuse_14            0
cyber_abuse_15            0
cyber_threat_1            0
cyber_threat_2_0          0
cyber_threat_2_1          0
cyber_threat_2_2          0
cyber_threat_2_3          0
cyber_threat_2_4          0
cyber_threat_2_5          0
cyber_threat_2_6          0
cyber_threat_2_7          0
cyber_threat_2_8          0
cyber_threat_3            0
cyber_threat_4_0          0
cyber_threat_4_1          0
cyber_threat_4_2          0
cyber_threat_4_3          0
cyber_threat_4_4          0
cyber_threat_4_5          0
cyber_threat_4_6          0
abuse_deg_1               0
abuse_deg_1a              0
abuse_deg_2               0
abuse_deg_2a              0
abuse_deg_3               0
abuse_deg_3a              0
abuse_deg_4               0
abuse_deg_4a              0
abuse_deg_5               0
abuse_deg_5a              0
abuse_deg_6               0
abuse_deg_6a              0
abuse_deg_7               0
abuse_deg_7a              0
abuse_deg_8               0
abuse_deg_8a              0
height                    0
weight                    0
bp_sys                    0
bp_dia                    0
pulse                     0
dtype: int64

# Remove Duplicate Records

In [18]:
df.duplicated().sum()

1

In [19]:
# Create a temporary dataframe of the duplicates
duplicates = df[df.duplicated(keep=False)]

# Show the duplicates
duplicates

,record_id,age,dob,sex,father_qualification,father_occupation,mother_qualification,mother_occupation,marital_status,income,...,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height,weight,bp_sys,bp_dia,pulse
1409,11019,17,2004-05-13,0,3,3,2,11,1,15000,...,-1,6,-1,6,-1,56.0,32.0,126,84,94
1410,11019,17,2004-05-13,0,3,3,2,11,1,15000,...,-1,6,-1,6,-1,56.0,32.0,126,84,94

In [20]:
# keep=False ensures you see all copies of the duplicate record_id(s)
duplicate_ids_df = df[df.duplicated(subset=['record_id'], keep=False)]

# Displaying duplicated IDs
duplicate_ids_df[['record_id']]

      record_id
102        1103
103        1103
124        1124
125        1124
1399      11014
1400      11014
1401      11015
1402      11015
1403      11016
1404      11016
1405      11017
1406      11017
1407      11018
1408      11018
1409      11019
1410      11019
1411      11020
1412      11020
1413      11021
1414      11021

## Now I am not only going to delete the "columns that have all the same values in all columns" but also the "first occurrences of every duplicate record_id".
## Let's consider that second occurrences are the updated ones and keep only that.

In [22]:
# Keep the last occurrence of each duplicate record_id
df = df.drop_duplicates(subset=["record_id"], keep="last")

# Verify that the duplicates are gone
print(f"Remaining duplicates: {df["record_id"].duplicated().sum()}")
print(f"New total row count: {len(df)}")

Remaining duplicates: 0
New total row count: 2020

# Categorizing data & Creating Features

In [24]:
columns = [
    'father_qualification',
    'father_occupation',
    'mother_qualification',
    'mother_occupation'
]

for col in columns:
    # Get unique values and sort them numerically
    unique_vals = np.sort(df[col].unique())
    
    print(f"\n{col} ({len(unique_vals)} unique values):")
    print(unique_vals)

father_qualification (8 unique values):
[ 1  2  3  4  5  6  7 88]

father_occupation (15 unique values):
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 88]

mother_qualification (8 unique values):
[ 1  2  3  4  5  6  7 88]

mother_occupation (14 unique values):
[ 1  2  3  6  7  8  9 10 11 12 13 14 15 88]

In [25]:
qualification_map = {
    1: 'No Formal Education',
    2: 'Primary',
    3: 'SSC',
    4: 'HSC',
    5: 'Diploma / Vocational',
    6: 'Graduate',
    7: 'Postgraduate',
    88: 'Jobless'
}

occupation_map = {
    1: 'Unemployed',
    2: 'Student',
    3: 'Agriculture / Farming',
    4: 'Business / Self-employed',
    5: 'Government Service',
    6: 'Private Service',
    7: 'Teaching / Education',
    8: 'Health Services',
    9: 'Technical / IT',
    10: 'Labour / Daily Wage',
    11: 'Police / Armed Forces',
    12: 'Retired',
    13: 'Other Occupations',
    14: 'Freelance / Contractual',
    15: 'Homemaker',
    88: 'Jobless'
}


df["father_qualification_category"] = df["father_qualification"].map(qualification_map)
df["mother_qualification_category"] = df["mother_qualification"].map(qualification_map)

df["father_occupation_category"] = df["father_occupation"].map(occupation_map)
df["mother_occupation_category"] = df["mother_occupation"].map(occupation_map)

In [26]:
# Socio-Economic Status based occupation groups

def occupation_group(occupation):
    if occupation in ['Unemployed', 'Jobless', 'Student', 'Homemaker', 'Retired']:
        return 'Not Economically Active'
    elif occupation in ['Labour / Daily Wage', 'Agriculture / Farming']:
        return 'Low Stability'
    elif occupation in ['Business / Self-employed', 'Freelance / Contractual']:
        return 'Medium Stability'
    elif occupation in ['Government Service', 'Private Service', 
                        'Teaching / Education', 'Health Services', 
                        'Technical / IT', 'Police / Armed Forces']:
        return 'High Stability'
    else:
        return 'Other'


df['father_occupation_group'] = df['father_occupation_category'].apply(occupation_group)
df['mother_occupation_group'] = df['mother_occupation_category'].apply(occupation_group)

In [27]:
df.head(5)

,record_id,age,dob,sex,father_qualification,father_occupation,mother_qualification,mother_occupation,marital_status,income,...,weight,bp_sys,bp_dia,pulse,father_qualification_category,mother_qualification_category,father_occupation_category,mother_occupation_category,father_occupation_group,mother_occupation_group
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,...,44.400002,105,65,74,Primary,Primary,Health Services,Police / Armed Forces,High Stability,High Stability
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,...,67.300003,123,78,69,No Formal Education,SSC,Health Services,Police / Armed Forces,High Stability,High Stability
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,...,59.500000,98,60,77,Primary,HSC,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,...,52.000000,98,62,84,SSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,...,48.700001,112,75,103,HSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability

## Sex

In [29]:
df['sex'].value_counts()

sex
1    1231
0     789
Name: count, dtype: int64

In [30]:
# In Bangladesh adolescent datasets:
    # Male count is often slightly higher
    # School surveys often have more boys than girls
# So, in this context, 1 will be male and 0 will be female.

df["sex_label"] = df["sex"].map({
    1: "Male", 
    0: "Female"
})

## Marital Status

In [32]:
df['marital_status'].value_counts()

marital_status
1     1819
5      124
2       53
4       16
3        5
88       3
Name: count, dtype: int64

In [33]:
marital_status_map = {
    1: 'Never Married',
    2: 'Divorced',
    3: 'Widowed', 
    4: 'Separated',
    5: 'Married',
    88: 'Not Reported'
}

df['marital_status_category'] = df['marital_status'].map(marital_status_map)

## Total Siblings & Total Family Member

In [35]:
df["total_siblings"] = df["brother"] + df["sister"]
df["total_family_members"] = df["family_member_male"] + df["family_member_female"]

In [36]:
# df.head(5)

In [37]:
# with pd.option_context("display.max_rows", None):
#     print(df['monthly_allowance'].value_counts())

## Monthly Allowance

In [39]:
# Then renaming 'income' to 'monthly_allowance'
df = df.rename(columns={'income': 'monthly_allowance'})

In [40]:
# categorize monthly_income

bins = [0, 10000, 20000, 40000, 80000, float("inf")]
labels = ["Very Low", "Low", "Medium", "High", "Very High"]

df["monthly_allowance_category"] = pd.cut(df["monthly_allowance"], bins=bins, labels=labels, right=True)

## FIES_total_score & Positive_parenting_total_score

In [42]:
df["Positive_parenting_total_score"] = df["alabama1"] + df["alabama2"] + df["alabama3"] + df["alabama4"] + df["alabama5"] + df["alabama6"] + df["alabama7"] + df["alabama8"] + df["alabama9"]

df["FIES_total_score"] = df["food1"] + df["food2"] + df["food3"] + df["food4"] + df["food5"] + df["food6"] + df["food7"] + df["food8"]

In [43]:
# df.head(5)

In [44]:
# categorizing FIES_total_score

def FIES_category(score):
    if score == 0:
        return "Food Secure"
    elif 1 <= score <= 3:
        return "Mild Food Insecurity"
    elif 4 <= score <= 6:
        return "Moderate Food Insecurity"
    else:
        return "Severe Food Insecurity"


df["FIES_category"] = df["FIES_total_score"].apply(FIES_category)

In [45]:
# df.head(5)

## Cyber Abuse, Cyber Threat, Abuse Degree

In [47]:
cyber_abuse_columns = [col for col in df.columns if col.startswith("cyber_abuse")]

cyber_threat_columns = [col for col in df.columns if col.startswith("cyber_threat")]

abuse_degree_columns = [col for col in df.columns if col.startswith("abuse_deg")]

In [48]:
# Replace ONLY negative values with 0

columns_to_clean = (
    cyber_abuse_columns +
    cyber_threat_columns +
    abuse_degree_columns
)

df[columns_to_clean] = df[columns_to_clean].clip(lower=0)     # clip(lower=0) -> Converts any negative value → 0

In [49]:
# Overall cyber abuse score
df["overall_cyber_abuse"] = df[cyber_abuse_columns].fillna(0).sum(axis=1)

# Overall cyber threat score
df["overall_cyber_threat"] = df[cyber_threat_columns].fillna(0).sum(axis=1)

# Overall abuse degree score
df["overall_abuse_degree"] = df[abuse_degree_columns].fillna(0).sum(axis=1)

In [125]:
df[['overall_cyber_abuse', 'overall_cyber_threat', 'overall_abuse_degree']].describe()

       overall_cyber_abuse  overall_abuse_degree
count          2020.000000           2020.000000
mean              6.127228             48.351980
std              11.982534              3.386506
min               1.000000             36.000000
25%               3.000000             48.000000
50%               6.000000             48.000000
75%               8.000000             48.000000
max             371.000000            142.000000

In [137]:
df[['overall_cyber_abuse', 'overall_cyber_threat', 'overall_abuse_degree']].dtypes

overall_cyber_abuse     float64
overall_cyber_threat     object
overall_abuse_degree      int64
dtype: object

In [139]:
# Convert "overall_cyber_threat" from object to float

df['overall_cyber_threat'] = pd.to_numeric(
    df['overall_cyber_threat'],
    errors='coerce'
).astype(float)

df['overall_cyber_threat'].dtype

dtype('float64')

In [143]:
df[['overall_cyber_abuse', 'overall_cyber_threat', 'overall_abuse_degree']].describe()

       overall_cyber_abuse  overall_cyber_threat  overall_abuse_degree
count          2020.000000           2020.000000           2020.000000
mean              6.127228              6.597525             48.351980
std              11.982534              2.770912              3.386506
min               1.000000              3.000000             36.000000
25%               3.000000              4.000000             48.000000
50%               6.000000              7.000000             48.000000
75%               8.000000              9.000000             48.000000
max             371.000000             14.000000            142.000000

In [146]:
with pd.option_context("display.max_rows", None):
    print(df['overall_cyber_abuse'].value_counts().sort_index())

overall_cyber_abuse
1.0      329
2.0      113
3.0      260
4.0      104
5.0      197
6.0       53
7.0      283
8.0      263
9.0      123
10.0     121
11.0      68
12.0      31
13.0      20
14.0      14
15.0      27
16.0       8
17.0       2
18.0       1
21.0       1
368.0      1
371.0      1
Name: count, dtype: int64

In [158]:
# Filtering out outliers from "overall_cyber_abuse"

max_abuse_score = len(cyber_abuse_columns)   # If I have 8 questions about cyber abuse (like harassment, hacking, etc.), len() will return 8. This is the "theoretical maximum" score a person can get if they answer "Yes" (1) to everything.

df.loc[df["overall_cyber_abuse"] > max_abuse_score, "overall_cyber_abuse"] = max_abuse_score

with pd.option_context("display.max_rows", None):
    print(df['overall_cyber_abuse'].value_counts().sort_index())

overall_cyber_abuse
1.0     329
2.0     113
3.0     260
4.0     104
5.0     197
6.0      53
7.0     283
8.0     263
9.0     123
10.0    121
11.0     68
12.0     31
13.0     20
14.0     14
15.0     27
16.0      8
17.0      2
18.0      1
21.0      1
30.0      2
Name: count, dtype: int64

In [162]:
# Categorizing "overall_cyber_abuse"

df["cyber_abuse_level"] = pd.cut(
    df["overall_cyber_abuse"], 
    bins = [0, 5, 10, 15, 20, max_abuse_score],
    labels = ["None / Minimal", "Low", "Moderate", "High", "Severe"]
)

In [148]:
with pd.option_context("display.max_rows", None):
    print(df['overall_cyber_threat'].value_counts().sort_index())

overall_cyber_threat
3.0     410
4.0     197
5.0     178
6.0     208
7.0     215
8.0     295
9.0     187
10.0    129
11.0    106
12.0     70
13.0     23
14.0      2
Name: count, dtype: int64

In [164]:
# Categorizing "overall_cyber_threat"

df["cyber_threat_level"] = pd.cut(
    df["overall_cyber_threat"], 
    bins = [0, 2, 5, 8, 10, float("inf")],
    labels = ["None / Minimal", "Low", "Moderate", "High", "Severe"]
)

In [150]:
with pd.option_context("display.max_rows", None):
    print(df['overall_abuse_degree'].value_counts().sort_index())

overall_abuse_degree
36        1
39        2
40        1
41        3
42        6
43        2
44       12
45       12
46       34
47       44
48     1753
49       34
50       23
51       18
52        9
53       11
54        8
55        8
56        3
57        7
58        4
59        4
60        2
62        1
63        2
64        4
65        1
66        1
67        1
68        1
69        1
70        1
71        1
78        1
82        1
83        1
95        1
142       1
Name: count, dtype: int64

In [180]:
# Categorizing "overall_abuse_degree"

df["abuse_degree_level"] = pd.cut(
    df["overall_abuse_degree"], 
    bins = [0, 40, 50, 60, 80, float("inf")],
    labels = ["None / Minimal", "Low", "Moderate", "High", "Severe"]
)

In [174]:
with pd.option_context("display.max_rows", None):
    print(df['cyber_abuse_level'].value_counts().sort_index())

cyber_abuse_level
None / Minimal    1003
Low                843
Moderate           160
High                11
Severe               3
Name: count, dtype: int64

## BMI

In [188]:
# Calculate BMI directly: weight / (height_in_inches * 0.0254)^2

df["BMI"] = (df["weight(kg)"] / ((df["height(inch)"] * 0.0254) ** 2)).round(2)

In [211]:
# BMI the teenagers

with pd.option_context("display.max_rows", None):
    print(df['BMI'].value_counts().sort_index())

BMI
11.05     1
12.06     1
12.44     1
12.50     1
12.60     1
12.70     1
12.86     1
13.22     1
13.35     6
13.43     1
13.51     2
13.52     1
13.57     1
13.61     1
13.63     1
13.67     2
13.71     1
13.76     1
13.78     1
13.80     1
13.81     1
13.84     1
13.91     1
13.92     1
13.94     1
13.98     2
14.03     1
14.05     1
14.15     1
14.16     3
14.19     1
14.21     2
14.25     1
14.28     2
14.31     1
14.32     1
14.35     2
14.38     4
14.42     1
14.43     1
14.45     4
14.52     3
14.55     1
14.57     1
14.58     4
14.59     2
14.60     1
14.64     3
14.66     3
14.69     2
14.70     1
14.73     1
14.74     1
14.75     1
14.76     1
14.78     1
14.84     3
14.85     1
14.86     2
14.87     1
14.91     1
14.94     4
14.95     2
14.98     1
15.00     2
15.02     1
15.03     1
15.04     2
15.07     4
15.08     2
15.09     1
15.12     1
15.13     1
15.14     7
15.16     2
15.19     3
15.20     1
15.21     1
15.23     2
15.24     1
15.25     2
15.27     1
15.30     3
15.32     6
15.33     2
15.34     1
15.35     1
15.36     1
15.39     1
15.41     7
15.46     1
15.48     2
15.50     8
15.52     3
15.54     4
15.56     2
15.58     6
15.60     1
15.62     6
15.63     2
15.64     1
15.66     3
15.67     1
15.69     1
15.70     1
15.71     1
15.72     2
15.73     9
15.74     5
15.75     4
15.78     2
15.80     1
15.81     1
15.82     3
15.83     6
15.84     1
15.86     1
15.87     1
15.88     2
15.89     5
15.92     1
15.93     5
15.94     1
15.95     1
15.97     5
15.99     2
16.00     4
16.01     5
16.03     7
16.05     1
16.07     1
16.08     1
16.09     3
16.11     1
16.12     1
16.13    14
16.14     4
16.15     1
16.16     1
16.17     1
16.19     2
16.21     2
16.22     3
16.23     1
16.24     1
16.25     4
16.26     1
16.27     2
16.28     1
16.29     2
16.30     1
16.31     7
16.32     3
16.33     1
16.35     3
16.36     7
16.37     3
16.39     1
16.40     3
16.41     1
16.43     3
16.45     3
16.46     1
16.47     1
16.48     4
16.50     1
16.51     6
16.52     1
16.53     4
16.54     1
16.55     3
16.57     1
16.59     7
16.60     2
16.64     1
16.65     6
16.66     7
16.68     1
16.70     2
16.72     1
16.73     3
16.75     2
16.76     1
16.77     1
16.79    17
16.80     2
16.82     1
16.83     1
16.84     1
16.86     3
16.87     1
16.88     6
16.90     1
16.92     9
16.93     2
16.94     9
16.95     2
16.96     2
16.97     1
16.99     2
17.00     1
17.01     2
17.02     1
17.03    12
17.05     5
17.06     1
17.08     7
17.09     2
17.10     4
17.11     1
17.12     3
17.13     2
17.14     1
17.16     1
17.17     5
17.18    10
17.19     1
17.20     2
17.22    17
17.23     1
17.24     3
17.25     1
17.26     6
17.27     2
17.28     2
17.30     3
17.32     2
17.34    11
17.35     1
17.36     2
17.37     9
17.38     2
17.39     1
17.41     4
17.42     5
17.43     1
17.44     8
17.45     1
17.48     3
17.50    12
17.51     9
17.52     2
17.54     2
17.57     4
17.58     5
17.60     1
17.61     4
17.62     2
17.64     1
17.65    21
17.66     2
17.67     1
17.68     1
17.69     2
17.71     2
17.74    11
17.75     3
17.77     1
17.78     1
17.79    15
17.81     9
17.82     3
17.83     3
17.84     1
17.86     1
17.87     2
17.88     1
17.89     1
17.90     2
17.91    11
17.92     2
17.93     2
17.94     3
17.95     2
17.96     7
17.97     7
17.98     4
18.00     2
18.01     1
18.02     3
18.03     1
18.04     2
18.05     1
18.07     2
18.08    11
18.09     1
18.10     2
18.12     1
18.13     4
18.15    15
18.16     7
18.20     1
18.22     2
18.23     1
18.26     4
18.27     1
18.28     1
18.29     3
18.30     5
18.31     1
18.32     1
18.33    10
18.34     5
18.35     8
18.36     1
18.37     5
18.39     3
18.43     6
18.44     3
18.45     5
18.46     2
18.47     1
18.48     1
18.50     6
18.51    10
18.52     1
18.54     6
18.55     7
18.56     1
18.57     1
18.58     1
18.60     3
18.61     3
18.63     2
18.64     1
18.65     2
18.66     1
18.68     1
18.70     7
18.71     4
18.73     1
18.74     8
18.75     6
18.77     3
18.78     4
18.79     2
18.80     1
18.81     1
18.82     2
18.83     2
18.84     1
18.86     2
18.87     1
18.88     2
18.89     8
18.90     3
18.91     1
18.92     6
18.94     7
18.95     7
18.96     1
18.97     2
18.99     2
19.03     2
19.04     2
19.05     1
19.07     1
19.08     1
19.09     1
19.10     1
19.11     2
19.12     2
19.13     1
19.14     4
19.15     8
19.16     7
19.17     2
19.19     2
19.20     1
19.21     3
19.22     1
19.24     3
19.25     1
19.27     1
19.29     2
19.30     7
19.31     2
19.32     1
19.33     1
19.34     1
19.35    16
19.38    10
19.41     3
19.43     1
19.44     6
19.46     1
19.47     3
19.49     1
19.50     2
19.53     2
19.54     2
19.55     3
19.56     6
19.57     3
19.58     7
19.59     8
19.60     1
19.61     1
19.63     2
19.64     3
19.66     1
19.67     1
19.68    10
19.70     2
19.71     1
19.72     3
19.73     1
19.75     4
19.76     8
19.77     3
19.78     1
19.80     1
19.81    17
19.84     2
19.85     1
19.86     1
19.88     2
19.89     1
19.90     4
19.91     1
19.92     2
19.93     5
19.94     1
19.95     1
19.96     1
19.98     3
19.99     7
20.01     1
20.02     2
20.03     2
20.04     8
20.06     6
20.08     1
20.09     1
20.10     1
20.11     2
20.13     1
20.14     1
20.15     1
20.16     4
20.17     1
20.18     6
20.19     1
20.20     1
20.23     1
20.24     9
20.25     1
20.26     1
20.27     4
20.28     4
20.29     1
20.31     5
20.32     1
20.37     2
20.39     1
20.41     2
20.42     1
20.43     6
20.45     1
20.46     3
20.47     1
20.48     4
20.50     1
20.51     3
20.54     5
20.56     8
20.58     1
20.60     1
20.62     4
20.64     5
20.66     2
20.67     6
20.68     1
20.69     1
20.70     7
20.72     2
20.73     3
20.76     1
20.78     1
20.79     1
20.80     1
20.81     3
20.83    12
20.84     1
20.85     1
20.86     1
20.87     1
20.88     1
20.89     1
20.90     2
20.91     1
20.92     1
20.93     4
20.95     3
20.96     1
20.97     5
20.99     1
21.01     1
21.06     2
21.07     1
21.08     1
21.09     8
21.10     6
21.13     1
21.15     1
21.16     2
21.17     1
21.19     3
21.20     5
21.23     1
21.24     8
21.25     2
21.26     1
21.28     4
21.29     2
21.33     1
21.35     2
21.37    10
21.38     2
21.41     1
21.44     1
21.45     1
21.46     2
21.47     4
21.48     4
21.49     2
21.51     4
21.52     3
21.53    12
21.56     1
21.57     2
21.59     1
21.60     1
21.61     2
21.65     3
21.66     5
21.70     1
21.71     2
21.72     1
21.76     1
21.77     7
21.79     2
21.81     1
21.82     2
21.83     2
21.85     1
21.87     2
21.94     2
21.95     6
21.96     4
21.98     2
21.99     1
22.01     2
22.03     1
22.05     2
22.06     4
22.07     1
22.08     1
22.10     3
22.12     5
22.13     1
22.14     2
22.18     3
22.20     3
22.22     1
22.23     1
22.24     3
22.26     2
22.30     1
22.33     2
22.38     4
22.39     7
22.40     1
22.44     2
22.46     2
22.49     5
22.55     2
22.56     1
22.58     5
22.60     1
22.62     1
22.65     5
22.70     1
22.71     4
22.74     1
22.76     1
22.77     1
22.79     2
22.80     1
22.82     3
22.84     1
22.86     1
22.91     2
22.98     3
23.03     1
23.04     5
23.06     1
23.08     3
23.09     1
23.11     1
23.13     3
23.14     1
23.15     6
23.18     1
23.19     1
23.20     3
23.23     2
23.24     1
23.29     2
23.33     1
23.36     2
23.38     1
23.39     2
23.41     1
23.43     4
23.46     1
23.48     6
23.50     1
23.53     1
23.55     1
23.58     2
23.60     4
23.63     2
23.67     2
23.68     3
23.72     1
23.79     2
23.82     2
23.84     5
23.85     3
23.89     1
23.93     1
23.94     1
23.96     1
24.04     6
24.06     1
24.07     2
24.09     1
24.10     1
24.11     1
24.13     2
24.14     1
24.16     1
24.19     2
24.20     1
24.21     3
24.22     2
24.24     1
24.28     1
24.30     1
24.31     2
24.37     1
24.41     1
24.45     2
24.46     1
24.47     1
24.48     1
24.49     2
24.52     1
24.53     3
24.54     4
24.55     2
24.60     3
24.65     1
24.70     1
24.79     1
24.81     1
24.84     1
24.87     1
24.88     1
24.91     1
24.94     3
24.95     1
24.99     1
25.00     3
25.05     1
25.11     1
25.20     2
25.22     1
25.25     1
25.27     1
25.31     1
25.34     2
25.36     1
25.39     2
25.40     5
25.41     2
25.42     1
25.43     1
25.48     2
25.51     1
25.56     1
25.58     1
25.62     2
25.64     1
25.66     1
25.70     3
25.80     5
25.81     3
25.83     5
25.89     1
25.92     1
25.93     1
25.94     1
25.95     1
26.04     2
26.12     1
26.24     4
26.26     2
26.27     1
26.37     2
26.41     1
26.49     1
26.56     1
26.57     1
26.65     1
26.66     2
26.69     1
26.72     1
26.82     1
26.92     1
26.93     1
26.94     2
26.95     3
27.02     1
27.05     1
27.08     1
27.09     1
27.11     1
27.12     1
27.17     1
27.25     1
27.28     1
27.34     1
27.38     1
27.42     2
27.43     2
27.49     1
27.67     1
27.73     1
27.82     2
27.87     1
27.99     2
28.05     3
28.07     1
28.10     1
28.11     2
28.18     2
28.19     1
28.23     1
28.36     2
28.40     1
28.43     1
28.50     1
28.62     1
28.82     1
28.97     1
29.02     1
29.03     2
29.14     1
29.28     1
29.32     1
29.35     1
29.39     1
29.50     1
29.52     1
29.58     1
29.59     1
29.62     1
29.84     1
30.07     1
30.08     1
30.25     1
30.37     1
30.38     1
30.44     1
30.57     2
30.78     1
31.01     1
31.11     1
31.24     1
31.30     1
31.33     1
31.61     1
32.07     1
32.11     1
32.25     1
32.42     1
32.65     1
32.68     1
32.74     1
32.88     1
32.96     2
33.02     1
33.03     1
33.19     1
33.35     2
33.47     1
34.27     1
34.73     1
34.80     1
34.82     1
35.09     1
36.51     1
38.17     1
39.72     1
41.40     1
41.66     1
Name: count, dtype: int64

## Health

In [192]:
# age of the teenagers

with pd.option_context("display.max_rows", None):
    print(df['age'].value_counts().sort_index())

age
14    584
15    501
16    458
17    291
18    161
19     25
Name: count, dtype: int64

In [260]:
def health_category_by_BMI(row):
    age = row['age']
    bmi = row['BMI']
    sex = row['sex_label']  # 'Male' or 'Female'
    
    if sex == 'Male':
        if 14 <= age <= 15:
            if bmi < 18.5: return 'Underweight'
            elif bmi <= 24.9: return 'Healthy'
            elif bmi <= 29.9: return 'Overweight'
            else: return 'Obese'
        elif 16 <= age <= 17:
            if bmi < 18.5: return 'Underweight'
            elif bmi <= 24.9: return 'Healthy'
            elif bmi <= 29.9: return 'Overweight'
            else: return 'Obese'
        elif 18 <= age <= 19:
            if bmi < 18.5: return 'Underweight'
            elif bmi <= 24.9: return 'Healthy'
            elif bmi <= 29.9: return 'Overweight'
            else: return 'Obese'
    else:  # Female
        if 14 <= age <= 15:
            if bmi < 18.5: return 'Underweight'
            elif bmi <= 22.9: return 'Healthy'
            elif bmi <= 28.9: return 'Overweight'
            else: return 'Obese'
        elif 16 <= age <= 17:
            if bmi < 18.5: return 'Underweight'
            elif bmi <= 23.9: return 'Healthy'
            elif bmi <= 28.9: return 'Overweight'
            else: return 'Obese'
        elif 18 <= age <= 19:
            if bmi < 18.5: return 'Underweight'
            elif bmi <= 22.9: return 'Healthy'
            elif bmi <= 28.9: return 'Overweight'
            else: return 'Obese'

df['health_category_by_BMI'] = df.apply(health_category_by_BMI, axis=1)

In [261]:
# health of the teenagers

with pd.option_context("display.max_rows", None):
    print(df['health_category_by_BMI'].value_counts().sort_index())

health_category_by_BMI
Healthy        896
Obese           43
Overweight     173
Underweight    908
Name: count, dtype: int64

In [280]:
# display(df)

## Other Health Features

In [270]:
# Mean Arterial Pressure (MAP)
df["Mean Arterial Pressure (MAP)"] = (2 * df["bp_dia"] + df["bp_sys"]) / 3

In [272]:
# Pulse Pressure (PP)
df["pulse_pressure"] = df["bp_sys"] - df["bp_dia"]

In [274]:
# Blood Pressure Category
def bp_category(row):
    sys = row["bp_sys"]
    dia = row["bp_dia"]

    if sys < 120 and dia <80:
        return "Normal"
    elif 120 <= sys < 130 and dia < 80:
        return "Elevated"
    elif 130 <= sys < 140 or 80 <= dia < 90:
        return "Hypertension Stage 1"
    elif sys >= 140 or dia >= 90:
        return "Hypertension Stage 2"
    else:
        return "Unknown"

df["bp_category"] = df.apply(bp_category, axis=1)

In [276]:
# Pulse Status
def pulse_status_adolescent(row):
    age = row["age"]
    sex = row["sex_label"]
    pulse = row["pulse"]

    if sex == "Male":
        if 14 <= age <= 15:
            return "Bradycardia" if pulse < 60 else "Tachycardia" if pulse > 95 else "Normal"
        elif 16 <= age <= 17:
            return "Bradycardia" if pulse < 60 else "Tachycardia" if pulse > 90 else "Normal"
        elif 18 <= age <= 19:
            return "Bradycardia" if pulse < 60 else "Tachycardia" if pulse > 85 else "Normal"

    else:    # "Female"
        if 14 <= age <= 15:
            return "Bradycardia" if pulse < 65 else "Tachycardia" if pulse > 100 else "Normal"
        elif 16 <= age <= 17:
            return "Bradycardia" if pulse < 65 else "Tachycardia" if pulse > 95 else "Normal"
        elif 18 <= age <= 19:
            return "Bradycardia" if pulse < 65 else "Tachycardia" if pulse > 95 else "Normal"


df["pulse_status"] = df.apply(pulse_status_adolescent, axis=1)

In [278]:
# Cardiovascular Risk Flag 
def cardio_risk(row):
    if row['bp_category'] in ['Hypertension Stage 1', 'Hypertension Stage 2'] or \
       row['pulse_status'] in ['Bradycardia', 'Tachycardia']:
        return 'At Risk'
    else:
        return 'Stable'

df['cardio_risk'] = df.apply(cardio_risk, axis=1)

In [282]:
# display(df)

,record_id,age,dob,sex,father_qualification,father_occupation,mother_qualification,mother_occupation,marital_status,monthly_allowance,brother,sister,family_member_male,family_member_female,telephone,mobile,television,radio,car,motor_cycle,bicycle,categorical_SWEMWS,categorical_AIS,alabama1,alabama2,alabama3,alabama4,alabama5,alabama6,alabama7,alabama8,alabama9,food1,food2,food3,food4,food5,food6,food7,food8,categorical_FIES,categorical_stress,categorical_Depression,categorical_Anxiety,cyber_abuse,cyber_abuse_2,cyber_abuse_3_1,cyber_abuse_3_2,cyber_abuse_3_3,cyber_abuse_3_4,cyber_abuse_3_5,cyber_abuse_4,cyber_abuse_5_1,cyber_abuse_5_2,cyber_abuse_5_3,cyber_abuse_6,cyber_abuse_7_1,cyber_abuse_7_2,cyber_abuse_7_3,cyber_abuse_7_4,cyber_abuse_7_5,cyber_abuse_7b_1,cyber_abuse_7b_2,cyber_abuse_7b_3,cyber_abuse_8,cyber_abuse_9_1,cyber_abuse_9_2,cyber_abuse_9_3,cyber_abuse_9_4,cyber_abuse_10,cyber_abuse_11,cyber_abuse_13,cyber_abuse_14,cyber_abuse_15,cyber_threat_1,cyber_threat_2_0,cyber_threat_2_1,cyber_threat_2_2,cyber_threat_2_3,cyber_threat_2_4,cyber_threat_2_5,cyber_threat_2_6,cyber_threat_2_7,cyber_threat_2_8,cyber_threat_3,cyber_threat_4_0,cyber_threat_4_1,cyber_threat_4_2,cyber_threat_4_3,cyber_threat_4_4,cyber_threat_4_5,cyber_threat_4_6,abuse_deg_1,abuse_deg_1a,abuse_deg_2,abuse_deg_2a,abuse_deg_3,abuse_deg_3a,abuse_deg_4,abuse_deg_4a,abuse_deg_5,abuse_deg_5a,abuse_deg_6,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height(inch),weight(kg),bp_sys,bp_dia,pulse,father_qualification_category,mother_qualification_category,father_occupation_category,mother_occupation_category,father_occupation_group,mother_occupation_group,sex_label,marital_status_category,total_siblings,total_family_members,monthly_allowance_category,Positive_parenting_total_score,FIES_total_score,FIES_category,overall_cyber_abuse,overall_cyber_threat,overall_abuse_degree,cyber_abuse_level,cyber_threat_level,abuse_degree_level,BMI,health_category_by_BMI,Mean Arterial Pressure (MAP),pulse_pressure,bp_category,pulse_status,cardio_risk
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,1,3,2,4,0,1,1,0,0,0,1,2,1,5,1,3,2,2,3,4,1,3,0,0,0,0,0,0,0,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,3,0,0,0,0,0,False,False,False,False,False,2,0,0,0,0,0,0,1,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,63.000000,44.400002,105,65,74,Primary,Primary,Health Services,Police / Armed Forces,High Stability,High Stability,Female,Never Married,4,6,Very Low,24,0,Food Secure,3.0,3.0,48,None / Minimal,Low,Low,17.34,Underweight,78.333333,40,Normal,Normal,Stable
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,2,0,3,1,0,1,1,0,0,0,1,2,1,5,3,5,3,1,5,5,1,3,1,1,1,0,1,0,0,0,2,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,1,0,0,0,0,0,False,False,False,False,False,2,0,1,0,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,68.000000,67.300003,123,78,69,No Formal Education,SSC,Health Services,Police / Armed Forces,High Stability,High Stability,Female,Never Married,2,4,Very Low,31,4,Moderate Food Insecurity,1.0,3.0,48,None / Minimal,Low,Low,22.56,Healthy,93.000000,45,Elevated,Normal,Stable
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,0,2,2,3,0,1,1,0,0,0,0,3,1,5,1,5,5,1,5,5,1,5,1,1,1,0,1,0,0,0,2,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,3,1,1,1,0,0,False,False,False,True,False,1,1,1,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,61.000000,59.500000,98,60,77,Primary,HSC,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability,Male,Never Married,2,5,Very Low,33,4,Moderate Food Insecurity,3.0,8.0,48,None / Minimal,Moderate,Low,24.79,Healthy,72.666667,38,Normal,Normal,Stable
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,0,1,3,4,0,1,1,0,0,0,1,2,1,5,3,5,3,1,5,5,1,5,1,1,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,1.0,0,0,0,0,0,0,0,0,False,False,False,False,False,2,1,0,0,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,61.000000,52.000000,98,62,84,SSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Never Married,1,7,Medium,33,2,Mild Food Insecurity,7.0,3.0,48,Low,Low,Low,21.66,Healthy,74.000000,36,Normal,Normal,Stable
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,1,1,2,3,0,1,1,0,0,0,0,2,1,5,3,1,3,1,5,5,1,4,0,0,0,0,0,0,0,0,1,2,4,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,1,1,1,0,0,False,False,False,False,False,3,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,5,1,6,0,6,0,6,0,57.000000,48.700001,112,75,103,HSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Never Married,2,5,Low,28,0,Food Secure,5.0,7.0,48,None / Minimal,Moderate,Low,23.23,Healthy,87.333333,37,Normal,Tachycardia,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,40017,16,2006-09-25,1,3,8,4,11,1,10000,1,2,2,3,0,1,0,0,0,0,0,1,1,5,3,5,5,5,5,5,4,4,0,0,0,0,0,0,0,0,1,1,3,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0.0,0,0,0,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,58.799999,46.000000,109,66,79,SSC,HSC,Health Services,Police / Armed Forces,High Stability,High Stability,Male,Never Married,3,5,Very Low,41,0,Food Secure,5.0,3.0,48,None / Minimal,Low,Low,20.62,Healthy,80.333333,43,Normal,Normal,Stable
2026,40018,16,2005-03-28,1,3,15,1,11,5,3000,1,3,1,3,0,1,0,0,0,0,0,1,1,5,5,5,4,1,5,5,4,3,1,1,1,1,1,1,1,0,3,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0.0,0,0,0,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,57.500000,36.000000,103,63,95,SSC,No Formal Education,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Married,4,4,Very Low,37,7,Severe Food Insecurity,5.0,3.0,48,None / Minimal,Low,Low,16.88,Underweight,76.333333,40,Normal,Tachycardia,At Risk
2027,50010,14,2006-05-28,1,3,3,2,11,1,20000,1,1,2,2,0,1,1,0,0,0,0,2,1,4,2,1,1,1,5,5,3,1,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,1,1,0,1,0,1,0,0,1,1.0,0,0,0,1,1,0,1,0,False,False,False,True,False,1,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,67.000000,93.000000,107,62,81,SSC,Primary,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability,Male,Never Married,2,4,Low,23,0,Food Secure,11.0,6.0,48,Moderate,Moderate,Low,32.11,Obese,77.000000,45,Normal,Normal,Stable
2028,90114,15,2008-06-06,1,2,9,2,11,1,13000,2,2,3,3,0,1,1,0,0,0,0,2,2,4,4,1,5,1,3,3,2,4,1,1,1,1,1,1,0,1,3,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,2,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,55.000000,42.000000,120,75,84,Primary,Primary,Technical / IT,Police / Armed Forces,High Stability,High Stability,Male,Never Married,4,6,Low,27,7,Severe Food Insecurity,2.0,3.0,48,None / Minimal,Low,Low,21.52,Healthy,90.000000,45,Elevated,Normal,Stable
2029,90117,14,2007-04-08,1,1,5,1,11,1,15000,1,2,4,2,0,1,1,0,0,0,0,2,1,5,5,1,5,1,5,5,1,5,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,1,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,62.000000,45.000000,118,74,89,No Formal Education,No Formal Education,Government Service,Police / Armed Forces,High Stability,High Stability,Male,Never Married,3,6,Low,33,0,Food Secure,3.0,3.0,48,None / Minimal,Low,Low,18.15,Underweight,88.666667,44,Normal,Normal,Stable

## Communication Access Score & Level

In [288]:
communication_columns = ["telephone", "mobile", "television", "radio"]
df["communication_access_score"] = df[communication_columns].sum(axis=1)

In [290]:
def communication_access_level(x):
    if x == 0:
        return "No Access"
    elif x <= 2:
        return "Limited Access"
    else:
        return "High Access"

df["communication_access_level"] = df["communication_access_score"].apply(communication_access_level)

## Transport Access Score & Level

In [302]:
transport_columns = ["car", "motor_cycle", "bicycle"]
df['transport_access_score'] = df[transport_columns].sum(axis=1)

In [309]:
def transport_access_level(x):
    if x == 0:
        return "No Transport"
    elif x == 1:
        return "Limited Transport"
    else:
        return "Multiple Transport Options"

df['transport_access_level'] = df['transport_access_score'].apply(transport_access_level)

In [315]:
display(df.columns)

Index(['record_id', 'age', 'dob', 'sex', 'father_qualification',
       'father_occupation', 'mother_qualification', 'mother_occupation',
       'marital_status', 'monthly_allowance',
       ...
       'health_category_by_BMI', 'Mean Arterial Pressure (MAP)',
       'pulse_pressure', 'bp_category', 'pulse_status', 'cardio_risk',
       'communication_access_score', 'communication_access_level',
       'transport_access_score', 'transport_access_level'],
      dtype='object', length=144)

## SWEMWS, AIS, FIES, stress, Depression, Anxiety

In [362]:
for col in [
    'categorical_SWEMWS',
    'categorical_AIS',
    'categorical_stress',
    'categorical_Depression',
    'categorical_Anxiety'
]:
    print(df[col].value_counts().sort_index())
    print('-'*40)

categorical_SWEMWS
1     597
2    1200
3     223
Name: count, dtype: int64
----------------------------------------
categorical_AIS
1    1653
2     255
3     112
Name: count, dtype: int64
----------------------------------------
categorical_stress
1    1706
2     165
3     103
4      40
5       6
Name: count, dtype: int64
----------------------------------------
categorical_Depression
1    1661
2     187
3     125
4      38
5       9
Name: count, dtype: int64
----------------------------------------
categorical_Anxiety
1    1740
2      90
3     134
4      32
5      24
Name: count, dtype: int64
----------------------------------------

In [356]:
# SWEMWS (Well-being)
swemws_map = {
    1: 'Low Wellbeing',
    2: 'Moderate Wellbeing',
    3: 'High Wellbeing'
}
df['SWEMWS_category'] = df['categorical_SWEMWS'].map(swemws_map)

In [358]:
# AIS (Insomnia)
ais_map = {
    1: 'No Insomnia',
    2: 'Moderate Insomnia',
    3: 'Severe Insomnia'
}
df['AIS_category'] = df['categorical_AIS'].map(ais_map)

In [360]:
# Stress
stress_map = {
    1: 'No Stress',
    2: 'Mild Stress',
    3: 'Moderate Stress',
    4: 'High Stress',
    5: 'Severe Stress'
}
df['Stress_category'] = df['categorical_stress'].map(stress_map)

In [366]:
# Depression
depression_map = {
    1: 'No Depression',
    2: 'Mild Depression',
    3: 'Moderate Depression',
    4: 'High Depression',
    5: 'Severe Depression'
}
df['Depression_category'] = df['categorical_Depression'].map(depression_map)

In [364]:
# Anxiety
anxiety_map = {
    1: 'No Anxiety',
    2: 'Mild Anxiety',
    3: 'Moderate Anxiety',
    4: 'High Anxiety',
    5: 'Severe Anxiety'
}
df['Anxiety_category'] = df['categorical_Anxiety'].map(anxiety_map)

In [368]:
# Fix SWEMWS direction 
# Because SWEMWS runs opposite, create a risk-aligned version.
# Now all mental health indicators point in the same direction.

risk_level = {
    1: 'High Risk',
    2: 'Moderate Risk',
    3: 'Low Risk'
}

df['SWEMWS_risk_level'] = df['categorical_SWEMWS'].map(risk_level)

In [ ]:
# Create aligned “risk” flags

df['stress_risk'] = df['categorical_stress'].apply(lambda x: 'At Risk' if x >= 3 else 'Low Risk') 
df['depression_risk'] = df['categorical_Depression'].apply(lambda x: 'At Risk' if x >= 3 else 'Low Risk') 
df['anxiety_risk'] = df['categorical_Anxiety'].apply(lambda x: 'At Risk' if x >= 3 else 'Low Risk') 
df['insomnia_risk'] = df['categorical_AIS'].apply(lambda x: 'At Risk' if x >= 2 else 'Low Risk')

In [370]:
# Create a unified mental health risk flag

    # Checks all four domains
    # If any one domain is at risk → At Risk
    # Else → Low Risk

df['any_mental_health_risk'] = df.apply(
    lambda row: 'At Risk' if (
        row['categorical_stress'] >= 3 or
        row['categorical_Depression'] >= 3 or
        row['categorical_Anxiety'] >= 3 or
        row['categorical_AIS'] >= 2
    ) else 'Low Risk',
    axis=1
)

In [372]:
display(df)

,record_id,age,dob,sex,father_qualification,father_occupation,mother_qualification,mother_occupation,marital_status,monthly_allowance,brother,sister,family_member_male,family_member_female,telephone,mobile,television,radio,car,motor_cycle,bicycle,categorical_SWEMWS,categorical_AIS,alabama1,alabama2,alabama3,alabama4,alabama5,alabama6,alabama7,alabama8,alabama9,food1,food2,food3,food4,food5,food6,food7,food8,categorical_FIES,categorical_stress,categorical_Depression,categorical_Anxiety,cyber_abuse,cyber_abuse_2,cyber_abuse_3_1,cyber_abuse_3_2,cyber_abuse_3_3,cyber_abuse_3_4,cyber_abuse_3_5,cyber_abuse_4,cyber_abuse_5_1,cyber_abuse_5_2,cyber_abuse_5_3,cyber_abuse_6,cyber_abuse_7_1,cyber_abuse_7_2,cyber_abuse_7_3,cyber_abuse_7_4,cyber_abuse_7_5,cyber_abuse_7b_1,cyber_abuse_7b_2,cyber_abuse_7b_3,cyber_abuse_8,cyber_abuse_9_1,cyber_abuse_9_2,cyber_abuse_9_3,cyber_abuse_9_4,cyber_abuse_10,cyber_abuse_11,cyber_abuse_13,cyber_abuse_14,cyber_abuse_15,cyber_threat_1,cyber_threat_2_0,cyber_threat_2_1,cyber_threat_2_2,cyber_threat_2_3,cyber_threat_2_4,cyber_threat_2_5,cyber_threat_2_6,cyber_threat_2_7,cyber_threat_2_8,cyber_threat_3,cyber_threat_4_0,cyber_threat_4_1,cyber_threat_4_2,cyber_threat_4_3,cyber_threat_4_4,cyber_threat_4_5,cyber_threat_4_6,abuse_deg_1,abuse_deg_1a,abuse_deg_2,abuse_deg_2a,abuse_deg_3,abuse_deg_3a,abuse_deg_4,abuse_deg_4a,abuse_deg_5,abuse_deg_5a,abuse_deg_6,abuse_deg_6a,abuse_deg_7,abuse_deg_7a,abuse_deg_8,abuse_deg_8a,height(inch),weight(kg),bp_sys,bp_dia,pulse,father_qualification_category,mother_qualification_category,father_occupation_category,mother_occupation_category,father_occupation_group,mother_occupation_group,sex_label,marital_status_category,total_siblings,total_family_members,monthly_allowance_category,Positive_parenting_total_score,FIES_total_score,FIES_category,overall_cyber_abuse,overall_cyber_threat,overall_abuse_degree,cyber_abuse_level,cyber_threat_level,abuse_degree_level,BMI,health_category_by_BMI,Mean Arterial Pressure (MAP),pulse_pressure,bp_category,pulse_status,cardio_risk,communication_access_score,communication_access_level,transport_access_score,transport_access_level,SWEMWS_category,AIS_category,Stress_category,Anxiety_category,Depression_category,SWEMWS_risk_level,any_mental_health_risk
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,1,3,2,4,0,1,1,0,0,0,1,2,1,5,1,3,2,2,3,4,1,3,0,0,0,0,0,0,0,0,1,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,3,0,0,0,0,0,False,False,False,False,False,2,0,0,0,0,0,0,1,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,63.000000,44.400002,105,65,74,Primary,Primary,Health Services,Police / Armed Forces,High Stability,High Stability,Female,Never Married,4,6,Very Low,24,0,Food Secure,3.0,3.0,48,None / Minimal,Low,Low,17.34,Underweight,78.333333,40,Normal,Normal,Stable,2,Limited Access,1,Limited Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,Mild Depression,Moderate Risk,Low Risk
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,2,0,3,1,0,1,1,0,0,0,1,2,1,5,3,5,3,1,5,5,1,3,1,1,1,0,1,0,0,0,2,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,1,0,0,0,0,0,False,False,False,False,False,2,0,1,0,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,68.000000,67.300003,123,78,69,No Formal Education,SSC,Health Services,Police / Armed Forces,High Stability,High Stability,Female,Never Married,2,4,Very Low,31,4,Moderate Food Insecurity,1.0,3.0,48,None / Minimal,Low,Low,22.56,Healthy,93.000000,45,Elevated,Normal,Stable,2,Limited Access,1,Limited Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,Mild Depression,Moderate Risk,Low Risk
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,0,2,2,3,0,1,1,0,0,0,0,3,1,5,1,5,5,1,5,5,1,5,1,1,1,0,1,0,0,0,2,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,3,1,1,1,0,0,False,False,False,True,False,1,1,1,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,61.000000,59.500000,98,60,77,Primary,HSC,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability,Male,Never Married,2,5,Very Low,33,4,Moderate Food Insecurity,3.0,8.0,48,None / Minimal,Moderate,Low,24.79,Healthy,72.666667,38,Normal,Normal,Stable,2,Limited Access,0,No Transport,High Wellbeing,No Insomnia,No Stress,Mild Anxiety,No Depression,Low Risk,Low Risk
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,0,1,3,4,0,1,1,0,0,0,1,2,1,5,3,5,3,1,5,5,1,5,1,1,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,1.0,0,0,0,0,0,0,0,0,False,False,False,False,False,2,1,0,0,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,61.000000,52.000000,98,62,84,SSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Never Married,1,7,Medium,33,2,Mild Food Insecurity,7.0,3.0,48,Low,Low,Low,21.66,Healthy,74.000000,36,Normal,Normal,Stable,2,Limited Access,1,Limited Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,Low Risk
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,1,1,2,3,0,1,1,0,0,0,0,2,1,5,3,1,3,1,5,5,1,4,0,0,0,0,0,0,0,0,1,2,4,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.0,0,0,1,1,1,1,0,0,False,False,False,False,False,3,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,5,1,6,0,6,0,6,0,57.000000,48.700001,112,75,103,HSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Never Married,2,5,Low,28,0,Food Secure,5.0,7.0,48,None / Minimal,Moderate,Low,23.23,Healthy,87.333333,37,Normal,Tachycardia,At Risk,2,Limited Access,0,No Transport,Moderate Wellbeing,No Insomnia,Mild Stress,No Anxiety,High Depression,Moderate Risk,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,40017,16,2006-09-25,1,3,8,4,11,1,10000,1,2,2,3,0,1,0,0,0,0,0,1,1,5,3,5,5,5,5,5,4,4,0,0,0,0,0,0,0,0,1,1,3,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0.0,0,0,0,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,58.799999,46.000000,109,66,79,SSC,HSC,Health Services,Police / Armed Forces,High Stability,High Stability,Male,Never Married,3,5,Very Low,41,0,Food Secure,5.0,3.0,48,None / Minimal,Low,Low,20.62,Healthy,80.333333,43,Normal,Normal,Stable,1,Limited Access,0,No Transport,Low Wellbeing,No Insomnia,No Stress,No Anxiety,Moderate Depression,High Risk,At Risk
2026,40018,16,2005-03-28,1,3,15,1,11,5,3000,1,3,1,3,0,1,0,0,0,0,0,1,1,5,5,5,4,1,5,5,4,3,1,1,1,1,1,1,1,0,3,1,1,3,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0.0,0,0,0,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,57.500000,36.000000,103,63,95,SSC,No Formal Education,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Married,4,4,Very Low,37,7,Severe Food Insecurity,5.0,3.0,48,None / Minimal,Low,Low,16.88,Underweight,76.333333,40,Normal,Tachycardia,At Risk,1,Limited Access,0,No Transport,Low Wellbeing,No Insomnia,No Stress,Moderate Anxiety,No Depression,High Risk,At Risk
2027,50010,14,2006-05-28,1,3,3,2,11,1,20000,1,1,2,2,0,1,1,0,0,0,0,2,1,4,2,1,1,1,5,5,3,1,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,1,1,0,1,0,1,0,0,1,1.0,0,0,0,1,1,0,1,0,False,False,False,True,False,1,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,67.000000,93.000000,107,62,81,SSC,Primary,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability,Male,Never Married,2,4,Low,23,0,Food Secure,11.0,6.0,48,Moderate,Moderate,Low,32.11,Obese,77.000000,45,Normal,Normal,Stable,2,Limited Access,0,No Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,Low Risk
2028,90114,15,2008-06-06,1,2,9,2,11,1,13000,2,2,3,3,0,1,1,0,0,0,0,2,2,4,4,1,5,1,3,3,2,4,1,1,1,1,1,1,0,1,3,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,2,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,55.000000,42.000000,120,75,84,Primary,Primary,Technical / IT,Police / Armed Forces,High Stability,High Stability,Male,Never Married,4,6,Low,27,7,Severe Food Insecurity,2.0,3.0,48,None / Minimal,Low,Low,21.52,Healthy,90.000000,45,Elevated,Normal,Stable,2,Limited Access,0,No Transport,Moderate Wellbeing,Moderate Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,At Risk
2029,90117,14,2007-04-08,1,1,5,1,11,1,15000,1,2,4,2,0,1,1,0,0,0,0,2,1,5,5,1,5,1,5,5,1,5,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,1,0,0,0,0,0,False,False,False,False,False,2,0,0,1,0,0,0,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,6,0,62.000000,45.000000,118,74,89,No Formal Education,No Formal Education,Government Service,Police / Armed Forces,High Stability,High Stability,Male,Never Married,3,6,Low,33,0,Food Secure,3.0,3.0,48,None / Minimal,Low,Low,18.15,Underweight,88.666667,44,Normal,Normal,Stable,2,Limited Access,0,No Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,Low Risk

In [374]:
with pd.option_context("display.max_rows", None):
    print(df['any_mental_health_risk'].value_counts().sort_index())

any_mental_health_risk
At Risk      763
Low Risk    1257
Name: count, dtype: int64

In [381]:
list(df.columns)

['record_id',
 'age',
 'dob',
 'sex',
 'father_qualification',
 'father_occupation',
 'mother_qualification',
 'mother_occupation',
 'marital_status',
 'monthly_allowance',
 'brother',
 'sister',
 'family_member_male',
 'family_member_female',
 'telephone',
 'mobile',
 'television',
 'radio',
 'car',
 'motor_cycle',
 'bicycle',
 'categorical_SWEMWS',
 'categorical_AIS',
 'alabama1',
 'alabama2',
 'alabama3',
 'alabama4',
 'alabama5',
 'alabama6',
 'alabama7',
 'alabama8',
 'alabama9',
 'food1',
 'food2',
 'food3',
 'food4',
 'food5',
 'food6',
 'food7',
 'food8',
 'categorical_FIES',
 'categorical_stress',
 'categorical_Depression',
 'categorical_Anxiety',
 'cyber_abuse',
 'cyber_abuse_2',
 'cyber_abuse_3_1',
 'cyber_abuse_3_2',
 'cyber_abuse_3_3',
 'cyber_abuse_3_4',
 'cyber_abuse_3_5',
 'cyber_abuse_4',
 'cyber_abuse_5_1',
 'cyber_abuse_5_2',
 'cyber_abuse_5_3',
 'cyber_abuse_6',
 'cyber_abuse_7_1',
 'cyber_abuse_7_2',
 'cyber_abuse_7_3',
 'cyber_abuse_7_4',
 'cyber_abuse_7_5',
 'cyber_abuse_7b_1',
 'cyber_abuse_7b_2',
 'cyber_abuse_7b_3',
 'cyber_abuse_8',
 'cyber_abuse_9_1',
 'cyber_abuse_9_2',
 'cyber_abuse_9_3',
 'cyber_abuse_9_4',
 'cyber_abuse_10',
 'cyber_abuse_11',
 'cyber_abuse_13',
 'cyber_abuse_14',
 'cyber_abuse_15',
 'cyber_threat_1',
 'cyber_threat_2_0',
 'cyber_threat_2_1',
 'cyber_threat_2_2',
 'cyber_threat_2_3',
 'cyber_threat_2_4',
 'cyber_threat_2_5',
 'cyber_threat_2_6',
 'cyber_threat_2_7',
 'cyber_threat_2_8',
 'cyber_threat_3',
 'cyber_threat_4_0',
 'cyber_threat_4_1',
 'cyber_threat_4_2',
 'cyber_threat_4_3',
 'cyber_threat_4_4',
 'cyber_threat_4_5',
 'cyber_threat_4_6',
 'abuse_deg_1',
 'abuse_deg_1a',
 'abuse_deg_2',
 'abuse_deg_2a',
 'abuse_deg_3',
 'abuse_deg_3a',
 'abuse_deg_4',
 'abuse_deg_4a',
 'abuse_deg_5',
 'abuse_deg_5a',
 'abuse_deg_6',
 'abuse_deg_6a',
 'abuse_deg_7',
 'abuse_deg_7a',
 'abuse_deg_8',
 'abuse_deg_8a',
 'height(inch)',
 'weight(kg)',
 'bp_sys',
 'bp_dia',
 'pulse',
 'father_qualification_category',
 'mother_qualification_category',
 'father_occupation_category',
 'mother_occupation_category',
 'father_occupation_group',
 'mother_occupation_group',
 'sex_label',
 'marital_status_category',
 'total_siblings',
 'total_family_members',
 'monthly_allowance_category',
 'Positive_parenting_total_score',
 'FIES_total_score',
 'FIES_category',
 'overall_cyber_abuse',
 'overall_cyber_threat',
 'overall_abuse_degree',
 'cyber_abuse_level',
 'cyber_threat_level',
 'abuse_degree_level',
 'BMI',
 'health_category_by_BMI',
 'Mean Arterial Pressure (MAP)',
 'pulse_pressure',
 'bp_category',
 'pulse_status',
 'cardio_risk',
 'communication_access_score',
 'communication_access_level',
 'transport_access_score',
 'transport_access_level',
 'SWEMWS_category',
 'AIS_category',
 'Stress_category',
 'Anxiety_category',
 'Depression_category',
 'SWEMWS_risk_level',
 'any_mental_health_risk']

In [384]:
# Save to CSV
df.to_csv(f"G:/DATA ANALYTICS PROJECTS/Project-7 [Silent Struggles]/Project/CSV/Dataset_with_new_necessary_features.csv", index=False)

# Creating Clean Dataset

In [387]:
patterns_to_drop = (
    "alabama", 
    "food", 
    "cyber_abuse", 
    "cyber_threat", 
    "abuse_deg"
)

columns_to_drop = [col for col in df.columns if col.startswith(patterns_to_drop)]

df_clean_Final = df.drop(columns=columns_to_drop)

In [391]:
display(df_clean_Final)

,record_id,age,dob,sex,father_qualification,father_occupation,mother_qualification,mother_occupation,marital_status,monthly_allowance,brother,sister,family_member_male,family_member_female,telephone,mobile,television,radio,car,motor_cycle,bicycle,categorical_SWEMWS,categorical_AIS,categorical_FIES,categorical_stress,categorical_Depression,categorical_Anxiety,height(inch),weight(kg),bp_sys,bp_dia,pulse,father_qualification_category,mother_qualification_category,father_occupation_category,mother_occupation_category,father_occupation_group,mother_occupation_group,sex_label,marital_status_category,total_siblings,total_family_members,monthly_allowance_category,Positive_parenting_total_score,FIES_total_score,FIES_category,overall_cyber_abuse,overall_cyber_threat,overall_abuse_degree,BMI,health_category_by_BMI,Mean Arterial Pressure (MAP),pulse_pressure,bp_category,pulse_status,cardio_risk,communication_access_score,communication_access_level,transport_access_score,transport_access_level,SWEMWS_category,AIS_category,Stress_category,Anxiety_category,Depression_category,SWEMWS_risk_level,any_mental_health_risk
0,1001,14,2006-12-18,0,2,8,2,11,1,10000,1,3,2,4,0,1,1,0,0,0,1,2,1,1,1,2,1,63.000000,44.400002,105,65,74,Primary,Primary,Health Services,Police / Armed Forces,High Stability,High Stability,Female,Never Married,4,6,Very Low,24,0,Food Secure,3.0,3.0,48,17.34,Underweight,78.333333,40,Normal,Normal,Stable,2,Limited Access,1,Limited Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,Mild Depression,Moderate Risk,Low Risk
1,1002,14,2007-03-17,0,1,8,3,11,1,8000,2,0,3,1,0,1,1,0,0,0,1,2,1,2,1,2,1,68.000000,67.300003,123,78,69,No Formal Education,SSC,Health Services,Police / Armed Forces,High Stability,High Stability,Female,Never Married,2,4,Very Low,31,4,Moderate Food Insecurity,1.0,3.0,48,22.56,Healthy,93.000000,45,Elevated,Normal,Stable,2,Limited Access,1,Limited Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,Mild Depression,Moderate Risk,Low Risk
2,1003,15,2005-08-13,1,2,3,4,11,1,7000,0,2,2,3,0,1,1,0,0,0,0,3,1,2,1,1,2,61.000000,59.500000,98,60,77,Primary,HSC,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability,Male,Never Married,2,5,Very Low,33,4,Moderate Food Insecurity,3.0,8.0,48,24.79,Healthy,72.666667,38,Normal,Normal,Stable,2,Limited Access,0,No Transport,High Wellbeing,No Insomnia,No Stress,Mild Anxiety,No Depression,Low Risk,Low Risk
3,1004,14,2006-12-18,1,3,15,3,11,1,25000,0,1,3,4,0,1,1,0,0,0,1,2,1,1,1,1,1,61.000000,52.000000,98,62,84,SSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Never Married,1,7,Medium,33,2,Mild Food Insecurity,7.0,3.0,48,21.66,Healthy,74.000000,36,Normal,Normal,Stable,2,Limited Access,1,Limited Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,Low Risk
4,1005,14,2006-10-17,1,4,15,3,11,1,20000,1,1,2,3,0,1,1,0,0,0,0,2,1,1,2,4,1,57.000000,48.700001,112,75,103,HSC,SSC,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Never Married,2,5,Low,28,0,Food Secure,5.0,7.0,48,23.23,Healthy,87.333333,37,Normal,Tachycardia,At Risk,2,Limited Access,0,No Transport,Moderate Wellbeing,No Insomnia,Mild Stress,No Anxiety,High Depression,Moderate Risk,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,40017,16,2006-09-25,1,3,8,4,11,1,10000,1,2,2,3,0,1,0,0,0,0,0,1,1,1,1,3,1,58.799999,46.000000,109,66,79,SSC,HSC,Health Services,Police / Armed Forces,High Stability,High Stability,Male,Never Married,3,5,Very Low,41,0,Food Secure,5.0,3.0,48,20.62,Healthy,80.333333,43,Normal,Normal,Stable,1,Limited Access,0,No Transport,Low Wellbeing,No Insomnia,No Stress,No Anxiety,Moderate Depression,High Risk,At Risk
2026,40018,16,2005-03-28,1,3,15,1,11,5,3000,1,3,1,3,0,1,0,0,0,0,0,1,1,3,1,1,3,57.500000,36.000000,103,63,95,SSC,No Formal Education,Homemaker,Police / Armed Forces,Not Economically Active,High Stability,Male,Married,4,4,Very Low,37,7,Severe Food Insecurity,5.0,3.0,48,16.88,Underweight,76.333333,40,Normal,Tachycardia,At Risk,1,Limited Access,0,No Transport,Low Wellbeing,No Insomnia,No Stress,Moderate Anxiety,No Depression,High Risk,At Risk
2027,50010,14,2006-05-28,1,3,3,2,11,1,20000,1,1,2,2,0,1,1,0,0,0,0,2,1,1,1,1,1,67.000000,93.000000,107,62,81,SSC,Primary,Agriculture / Farming,Police / Armed Forces,Low Stability,High Stability,Male,Never Married,2,4,Low,23,0,Food Secure,11.0,6.0,48,32.11,Obese,77.000000,45,Normal,Normal,Stable,2,Limited Access,0,No Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,Low Risk
2028,90114,15,2008-06-06,1,2,9,2,11,1,13000,2,2,3,3,0,1,1,0,0,0,0,2,2,3,1,1,1,55.000000,42.000000,120,75,84,Primary,Primary,Technical / IT,Police / Armed Forces,High Stability,High Stability,Male,Never Married,4,6,Low,27,7,Severe Food Insecurity,2.0,3.0,48,21.52,Healthy,90.000000,45,Elevated,Normal,Stable,2,Limited Access,0,No Transport,Moderate Wellbeing,Moderate Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,At Risk
2029,90117,14,2007-04-08,1,1,5,1,11,1,15000,1,2,4,2,0,1,1,0,0,0,0,2,1,1,1,1,1,62.000000,45.000000,118,74,89,No Formal Education,No Formal Education,Government Service,Police / Armed Forces,High Stability,High Stability,Male,Never Married,3,6,Low,33,0,Food Secure,3.0,3.0,48,18.15,Underweight,88.666667,44,Normal,Normal,Stable,2,Limited Access,0,No Transport,Moderate Wellbeing,No Insomnia,No Stress,No Anxiety,No Depression,Moderate Risk,Low Risk

In [393]:
list(df_clean_Final.columns)

['record_id',
 'age',
 'dob',
 'sex',
 'father_qualification',
 'father_occupation',
 'mother_qualification',
 'mother_occupation',
 'marital_status',
 'monthly_allowance',
 'brother',
 'sister',
 'family_member_male',
 'family_member_female',
 'telephone',
 'mobile',
 'television',
 'radio',
 'car',
 'motor_cycle',
 'bicycle',
 'categorical_SWEMWS',
 'categorical_AIS',
 'categorical_FIES',
 'categorical_stress',
 'categorical_Depression',
 'categorical_Anxiety',
 'height(inch)',
 'weight(kg)',
 'bp_sys',
 'bp_dia',
 'pulse',
 'father_qualification_category',
 'mother_qualification_category',
 'father_occupation_category',
 'mother_occupation_category',
 'father_occupation_group',
 'mother_occupation_group',
 'sex_label',
 'marital_status_category',
 'total_siblings',
 'total_family_members',
 'monthly_allowance_category',
 'Positive_parenting_total_score',
 'FIES_total_score',
 'FIES_category',
 'overall_cyber_abuse',
 'overall_cyber_threat',
 'overall_abuse_degree',
 'BMI',
 'health_category_by_BMI',
 'Mean Arterial Pressure (MAP)',
 'pulse_pressure',
 'bp_category',
 'pulse_status',
 'cardio_risk',
 'communication_access_score',
 'communication_access_level',
 'transport_access_score',
 'transport_access_level',
 'SWEMWS_category',
 'AIS_category',
 'Stress_category',
 'Anxiety_category',
 'Depression_category',
 'SWEMWS_risk_level',
 'any_mental_health_risk']

In [399]:
# Save to CSV
df_clean_Final.to_csv(f"G:/DATA ANALYTICS PROJECTS/Project-7 [Silent Struggles]/Project/CSV/FINAL_Clean_Dataset.csv", index=False)

In [409]:
for col, dtype in df_clean_Final.dtypes.items():
    print(f"{col}: {dtype}")

record_id: int64
age: int64
dob: object
sex: int64
father_qualification: int64
father_occupation: int64
mother_qualification: int64
mother_occupation: int64
marital_status: int64
monthly_allowance: int64
brother: int64
sister: int64
family_member_male: int64
family_member_female: int64
telephone: int64
mobile: int64
television: int64
radio: int64
car: int64
motor_cycle: int64
bicycle: int64
categorical_SWEMWS: int64
categorical_AIS: int64
categorical_FIES: int64
categorical_stress: int64
categorical_Depression: int64
categorical_Anxiety: int64
height(inch): float64
weight(kg): float64
bp_sys: int64
bp_dia: int64
pulse: int64
father_qualification_category: object
mother_qualification_category: object
father_occupation_category: object
mother_occupation_category: object
father_occupation_group: object
mother_occupation_group: object
sex_label: object
marital_status_category: object
total_siblings: int64
total_family_members: int64
monthly_allowance_category: category
Positive_parenting_total_score: int64
FIES_total_score: int64
FIES_category: object
overall_cyber_abuse: float64
overall_cyber_threat: float64
overall_abuse_degree: int64
BMI: float64
health_category_by_BMI: object
Mean Arterial Pressure (MAP): float64
pulse_pressure: int64
bp_category: object
pulse_status: object
cardio_risk: object
communication_access_score: int64
communication_access_level: object
transport_access_score: int64
transport_access_level: object
SWEMWS_category: object
AIS_category: object
Stress_category: object
Anxiety_category: object
Depression_category: object
SWEMWS_risk_level: object
any_mental_health_risk: object

In [401]:
for col in [
    'record_id',
    'age',
    'dob',
    'sex',
    'father_qualification',
    'father_occupation',
    'mother_qualification',
    'mother_occupation',
    'marital_status',
    'monthly_allowance',
    'brother',
    'sister',
    'family_member_male',
    'family_member_female',
    'telephone',
    'mobile',
    'television',
    'radio',
    'car',
    'motor_cycle',
    'bicycle',
    'categorical_SWEMWS',
    'categorical_AIS',
    'categorical_FIES',
    'categorical_stress',
    'categorical_Depression',
    'categorical_Anxiety',
    'height(inch)',
    'weight(kg)',
    'bp_sys',
    'bp_dia',
    'pulse',
    'father_qualification_category',
    'mother_qualification_category',
    'father_occupation_category',
    'mother_occupation_category',
    'father_occupation_group',
    'mother_occupation_group',
    'sex_label',
    'marital_status_category',
    'total_siblings',
    'total_family_members',
    'monthly_allowance_category',
    'Positive_parenting_total_score',
    'FIES_total_score',
    'FIES_category',
    'overall_cyber_abuse',
    'overall_cyber_threat',
    'overall_abuse_degree',
    'BMI',
    'health_category_by_BMI',
    'Mean Arterial Pressure (MAP)',
    'pulse_pressure',
    'bp_category',
    'pulse_status',
    'cardio_risk',
    'communication_access_score',
    'communication_access_level',
    'transport_access_score',
    'transport_access_level',
    'SWEMWS_category',
    'AIS_category',
    'Stress_category',
    'Anxiety_category',
    'Depression_category',
    'SWEMWS_risk_level',
    'any_mental_health_risk'
]:
    print(df[col].value_counts().sort_index())
    print('-'*40)

record_id
1001     1
1002     1
1003     1
1004     1
1005     1
        ..
40017    1
40018    1
50010    1
90114    1
90117    1
Name: count, Length: 2020, dtype: int64
----------------------------------------
age
14    584
15    501
16    458
17    291
18    161
19     25
Name: count, dtype: int64
----------------------------------------
dob
2002-01-01    2
2002-01-03    1
2002-01-14    2
2002-01-16    1
2002-02-08    1
             ..
2026-11-17    1
2027-01-01    1
2027-03-13    1
2027-03-29    1
2028-01-26    1
Name: count, Length: 1122, dtype: int64
----------------------------------------
sex
0     789
1    1231
Name: count, dtype: int64
----------------------------------------
father_qualification
1     324
2     389
3     663
4     283
5     155
6     111
7      55
88     40
Name: count, dtype: int64
----------------------------------------
father_occupation
1      73
2     271
3     481
4     132
5     183
6      82
7      27
8     324
9     129
11      4
12     11
13     22
14     40
15    238
88      3
Name: count, dtype: int64
----------------------------------------
mother_qualification
1     258
2     435
3     810
4     315
5     113
6      57
7      26
88      6
Name: count, dtype: int64
----------------------------------------
mother_occupation
1       30
2      108
3       12
6        1
7       35
8       36
9       41
10       3
11    1718
12       1
13       3
14       2
15      28
88       2
Name: count, dtype: int64
----------------------------------------
marital_status
1     1819
2       53
3        5
4       16
5      124
88       3
Name: count, dtype: int64
----------------------------------------
monthly_allowance
3000      12
4000       8
4500       3
5000      40
5500       1
          ..
100000     4
120000     2
150000     2
200000     1
250001     1
Name: count, Length: 62, dtype: int64
----------------------------------------
brother
0    354
1    888
2    545
3    167
4     52
5     13
6      1
Name: count, dtype: int64
----------------------------------------
sister
0    329
1    818
2    568
3    214
4     67
5     17
6      4
7      2
9      1
Name: count, dtype: int64
----------------------------------------
family_member_male
0      22
1     352
2     815
3     538
4     207
5      60
6      16
7       4
9       3
13      3
Name: count, dtype: int64
----------------------------------------
family_member_female
1     295
2     757
3     576
4     248
5      83
6      36
7      16
8       3
9       3
13      3
Name: count, dtype: int64
----------------------------------------
telephone
0    1916
1     104
Name: count, dtype: int64
----------------------------------------
mobile
0      20
1    2000
Name: count, dtype: int64
----------------------------------------
television
0     383
1    1637
Name: count, dtype: int64
----------------------------------------
radio
0    1990
1      30
Name: count, dtype: int64
----------------------------------------
car
0    2004
1      16
Name: count, dtype: int64
----------------------------------------
motor_cycle
0    1874
1     146
Name: count, dtype: int64
----------------------------------------
bicycle
0    1429
1     591
Name: count, dtype: int64
----------------------------------------
categorical_SWEMWS
1     597
2    1200
3     223
Name: count, dtype: int64
----------------------------------------
categorical_AIS
1    1653
2     255
3     112
Name: count, dtype: int64
----------------------------------------
categorical_FIES
1    1570
2     293
3     157
Name: count, dtype: int64
----------------------------------------
categorical_stress
1    1706
2     165
3     103
4      40
5       6
Name: count, dtype: int64
----------------------------------------
categorical_Depression
1    1661
2     187
3     125
4      38
5       9
Name: count, dtype: int64
----------------------------------------
categorical_Anxiety
1    1740
2      90
3     134
4      32
5      24
Name: count, dtype: int64
----------------------------------------
height(inch)
40.000000      1
46.000000      2
47.000000      1
48.000000      4
48.799999      1
49.000000      3
50.000000      3
51.000000      1
52.000000      9
53.000000     10
54.000000     17
55.000000     31
55.599998      1
56.000000     48
56.599998      1
57.000000     75
57.500000      2
57.599998      1
57.799999      1
58.000000    138
58.400002      1
58.500000      1
58.799999      1
59.000000    181
59.299999      1
59.400002      1
59.500000      1
60.000000    261
60.200001      1
60.500000      2
60.599998      1
61.000000    219
61.200001      3
61.500000      3
62.000000    244
62.200001      2
62.299999      1
62.500000      2
63.000000    178
63.500000      1
63.799999      1
64.000000    173
64.400002      1
64.500000      3
65.000000    130
65.400002      1
66.000000     94
67.000000     66
68.000000     44
69.000000     30
70.000000     10
71.000000      3
72.000000      7
73.000000      1
76.000000      1
Name: count, dtype: int64
----------------------------------------
weight(kg)
26.299999     1
27.000000     2
27.350000     1
28.000000     1
28.850000     1
             ..
90.000000     1
90.900002     3
93.000000     1
100.000000    1
101.000000    1
Name: count, Length: 450, dtype: int64
----------------------------------------
bp_sys
66     1
73     2
75     2
77     4
78     1
      ..
150    1
152    1
153    2
155    1
158    2
Name: count, Length: 79, dtype: int64
----------------------------------------
bp_dia
43     1
45     1
46     1
47     1
48     3
      ..
102    2
106    2
109    1
112    1
131    1
Name: count, Length: 62, dtype: int64
----------------------------------------
pulse
41     1
47     2
48     2
49     1
53     2
      ..
128    6
129    2
130    4
145    1
149    1
Name: count, Length: 84, dtype: int64
----------------------------------------
father_qualification_category
Diploma / Vocational    155
Graduate                111
HSC                     283
Jobless                  40
No Formal Education     324
Postgraduate             55
Primary                 389
SSC                     663
Name: count, dtype: int64
----------------------------------------
mother_qualification_category
Diploma / Vocational    113
Graduate                 57
HSC                     315
Jobless                   6
No Formal Education     258
Postgraduate             26
Primary                 435
SSC                     810
Name: count, dtype: int64
----------------------------------------
father_occupation_category
Agriculture / Farming       481
Business / Self-employed    132
Freelance / Contractual      40
Government Service          183
Health Services             324
Homemaker                   238
Jobless                       3
Other Occupations            22
Police / Armed Forces         4
Private Service              82
Retired                      11
Student                     271
Teaching / Education         27
Technical / IT              129
Unemployed                   73
Name: count, dtype: int64
----------------------------------------
mother_occupation_category
Agriculture / Farming        12
Freelance / Contractual       2
Health Services              36
Homemaker                    28
Jobless                       2
Labour / Daily Wage           3
Other Occupations             3
Police / Armed Forces      1718
Private Service               1
Retired                       1
Student                     108
Teaching / Education         35
Technical / IT               41
Unemployed                   30
Name: count, dtype: int64
----------------------------------------
father_occupation_group
High Stability             749
Low Stability              481
Medium Stability           172
Not Economically Active    596
Other                       22
Name: count, dtype: int64
----------------------------------------
mother_occupation_group
High Stability             1831
Low Stability                15
Medium Stability              2
Not Economically Active     169
Other                         3
Name: count, dtype: int64
----------------------------------------
sex_label
Female     789
Male      1231
Name: count, dtype: int64
----------------------------------------
marital_status_category
Divorced           53
Married           124
Never Married    1819
Not Reported        3
Separated          16
Widowed             5
Name: count, dtype: int64
----------------------------------------
total_siblings
1     126
2     762
3     671
4     301
5     103
6      35
7      18
8       2
9       1
11      1
Name: count, dtype: int64
----------------------------------------
total_family_members
1       1
2      12
3     163
4     675
5     570
6     322
7     147
8      68
9      20
10     18
11      4
12      9
13      4
14      1
17      3
26      3
Name: count, dtype: int64
----------------------------------------
monthly_allowance_category
Very Low     655
Low          895
Medium       347
High         108
Very High     15
Name: count, dtype: int64
----------------------------------------
Positive_parenting_total_score
9       3
11      1
13      1
15      5
16     15
17     28
18     40
19     31
20     40
21     62
22     73
23     80
24     73
25    111
26     93
27    132
28    126
29    144
30    144
31    135
32    110
33    141
34    105
35     95
36     62
37     48
38     36
39     23
40     28
41     21
42      3
43      7
44      1
45      3
Name: count, dtype: int64
----------------------------------------
FIES_total_score
0    1012
1     135
2     269
3     154
4     154
5      81
6      58
7      96
8      61
Name: count, dtype: int64
----------------------------------------
FIES_category
Food Secure                 1012
Mild Food Insecurity         558
Moderate Food Insecurity     293
Severe Food Insecurity       157
Name: count, dtype: int64
----------------------------------------
overall_cyber_abuse
1.0     329
2.0     113
3.0     260
4.0     104
5.0     197
6.0      53
7.0     283
8.0     263
9.0     123
10.0    121
11.0     68
12.0     31
13.0     20
14.0     14
15.0     27
16.0      8
17.0      2
18.0      1
21.0      1
30.0      2
Name: count, dtype: int64
----------------------------------------
overall_cyber_threat
3.0     410
4.0     197
5.0     178
6.0     208
7.0     215
8.0     295
9.0     187
10.0    129
11.0    106
12.0     70
13.0     23
14.0      2
Name: count, dtype: int64
----------------------------------------
overall_abuse_degree
36        1
39        2
40        1
41        3
42        6
43        2
44       12
45       12
46       34
47       44
48     1753
49       34
50       23
51       18
52        9
53       11
54        8
55        8
56        3
57        7
58        4
59        4
60        2
62        1
63        2
64        4
65        1
66        1
67        1
68        1
69        1
70        1
71        1
78        1
82        1
83        1
95        1
142       1
Name: count, dtype: int64
----------------------------------------
BMI
11.05    1
12.06    1
12.44    1
12.50    1
12.60    1
        ..
36.51    1
38.17    1
39.72    1
41.40    1
41.66    1
Name: count, Length: 808, dtype: int64
----------------------------------------
health_category_by_BMI
Healthy        896
Obese           43
Overweight     173
Underweight    908
Name: count, dtype: int64
----------------------------------------
Mean Arterial Pressure (MAP)
53.666667     1
58.000000     1
59.666667     3
60.000000     2
60.333333     1
             ..
116.000000    1
116.333333    1
117.333333    1
117.666667    1
138.333333    1
Name: count, Length: 161, dtype: int64
----------------------------------------
pulse_pressure
3     1
7     1
11    2
12    1
13    1
     ..
68    1
70    2
71    1
72    1
75    1
Name: count, Length: 64, dtype: int64
----------------------------------------
bp_category
Elevated                 162
Hypertension Stage 1     416
Hypertension Stage 2      68
Normal                  1374
Name: count, dtype: int64
----------------------------------------
pulse_status
Bradycardia      72
Normal         1373
Tachycardia     575
Name: count, dtype: int64
----------------------------------------
cardio_risk
At Risk     929
Stable     1091
Name: count, dtype: int64
----------------------------------------
communication_access_score
0      11
1     356
2    1547
3     103
4       3
Name: count, dtype: int64
----------------------------------------
communication_access_level
High Access        106
Limited Access    1903
No Access           11
Name: count, dtype: int64
----------------------------------------
transport_access_score
0    1344
1     603
2      69
3       4
Name: count, dtype: int64
----------------------------------------
transport_access_level
Limited Transport              603
Multiple Transport Options      73
No Transport                  1344
Name: count, dtype: int64
----------------------------------------
SWEMWS_category
High Wellbeing         223
Low Wellbeing          597
Moderate Wellbeing    1200
Name: count, dtype: int64
----------------------------------------
AIS_category
Moderate Insomnia     255
No Insomnia          1653
Severe Insomnia       112
Name: count, dtype: int64
----------------------------------------
Stress_category
High Stress          40
Mild Stress         165
Moderate Stress     103
No Stress          1706
Severe Stress         6
Name: count, dtype: int64
----------------------------------------
Anxiety_category
High Anxiety          32
Mild Anxiety          90
Moderate Anxiety     134
No Anxiety          1740
Severe Anxiety        24
Name: count, dtype: int64
----------------------------------------
Depression_category
High Depression          38
Mild Depression         187
Moderate Depression     125
No Depression          1661
Severe Depression         9
Name: count, dtype: int64
----------------------------------------
SWEMWS_risk_level
High Risk         597
Low Risk          223
Moderate Risk    1200
Name: count, dtype: int64
----------------------------------------
any_mental_health_risk
At Risk      763
Low Risk    1257
Name: count, dtype: int64
----------------------------------------